DROP DATABASE IF EXISTS MemeGenerator;
CREATE DATABASE MemeGenerator;

USE MemeGenerator;


CREATE Table Tag (
id INT UNSIGNED PRIMARY KEY,
name VARCHAR(32)
};

CREATE TABLE Template (
id INT UNSIGNED PRIMARY KEY,
image MEDIUMBLOB
);

CREATE TABLE Text (
id INT UNSIGNED PRIMARY KEY,
top VARCHAR(128),
bottom VARCHAR(128)
);

CREATE TABLE Like_Reaction (
id INT UNSIGNED PRIMARY KEY,
memeid INT UNSIGNED,
userid INT UNSIGNED,
reactionid INT UNSIGNED
FOREIGN KEY (userid) REFERENCES User (id),
FOREIGN KEY (memeid) REFERENCES Meme (id)
);

CREATE TABLE Comment (
id INT UNSIGNED PRIMARY KEY
userid INT UNSIGNED,
memeid INT UNSIGNED,
comment VARCHAR(512)
FOREIGN KEY (userid) REFERENCES User (id),
FOREIGN KEY (memeid) REFERENCES Meme (id)
);

CREATE TABLE Meme (
id INT UNSIGNED PRIMARY KEY,
templateid INT UNSIGNED,
textid INT UNSIGNED,
meme MEDIUMBLOB,
FOREIGN KEY (templateid) REFERENCES Template (id),
FOREIGN KEY (textid) REFERENCES Text (id)
);

CREATE TABLE User (
id INT UNSIGNED PRIMARY KEY,
login VARCHAR(32)
);

CREATE TABLE MemeTag (
id INT UNSIGNED PRIMARY KEY,
memeid INT UNSIGNED,
tagid INT UNSIGNED,
FOREIGN KEY (memeid) REFERENCES Meme (id),
FOREIGN KEY (tagid) REFERENCES Tag (id)
);

CREATE TABLE UserTemplate (
id INT UNSIGNED PRIMARY KEY,
userid INT UNSIGNED,
templateid INT UNSIGNED,
FOREIGN KEY (userid) REFERENCES User (id),
FOREIGN KEY (templateid) REFERENCES Template (id)
);

CREATE TABLE TagUser (
id INT UNSIGNED PRIMARY KEY,
userid INT UNSIGNED,
tagid INT UNSIGNED,

FOREIGN KEY (userid) REFERENCES User (id),
FOREIGN KEY (tagid) REFERENCES Tag (id)
);

INSERT INTO 


